### ISSUE TITLE
Workflow doesn't push to index

### ISSUE THREAD

**Issue by cameronos** [cameronos/optifinestatus#1]
When a health-check is performed, the health-check doesn't post the results to the specified log directory or the index.html. Simple fix with change of .sh

**Comment by cameronos** [comment]
Fixed in [f9d7611](https://github.com/cameronos/optifinestatus/commit/f9d76118d44ff53620d575e7a81e770737a53bfc)

**Comment by cameronos** [comment]
Still present after [f9d7611](https://github.com/cameronos/optifinestatus/commit/f9d76118d44ff53620d575e7a81e770737a53bfc), now results with a 'line 35: [: : integer expression expected' error

**Comment by cameronos** [comment]
Tested update & possible fix in [7148edc](https://github.com/cameronos/optifinestatus/commit/7148edc4037a9e50c16a18f3b41200d406f60652)

**Comment by cameronos** [comment]
Curl present with same error

**Comment by TerraceStomp** [comment]
Still present with [5453600175](https://github.com/cameronos/optifinestatus/runs/5453600175?check_suite_focus=true), caused by hanging integer in shellscript. CFG doesn't update real-time either

**Comment by TerraceStomp** [comment]
Fixed in commit [296540fd7723a149182dceede975ecbb3b8fb620](https://github.com/cameronos/optifinestatus/commit/296540fd7723a149182dceede975ecbb3b8fb620). Closing issue
